### PR TITLE
 Added warning to TF docs on how it blocks all GPU memory on nodes

### PR DESCRIPTION
**Pull request by twinkarma**
... and how to resolve it with the deviceSelect.sh written by @ptheywood

### CODE REVIEW

**Comment by willfurnass** [comment]
Script doesn't account for the user requesting >1 GPU (or parallel jobs (MPI or SMP)). 

A cleaner approach is to enable the GPU locking epilog/prolog scripts on the public GPU nodes; this has been approved recently.  However, your doc suggestions would be useful in the interim if the aforementioned deficiencies in the script can be addressed (for the >1GPU and SMP job cases at least).

**Comment by ptheywood** [comment]
I've created an updated version of the device selection script which can account for multiple devices including parallel jobs (thanks to @willfurnass). 

It also resolves a bug with the previous script, where the device indices returned by nvidia-smi are not the same as when enumerated as a part of `CUDA_VISIBLE_DEVICES` (via `CUDA_DEVICE_ORDER=PCI_BUS_ID`)

https://gist.github.com/ptheywood/ce4e5a600216dd085cae5bd5802d35aa

**Comment by twinkarma** [comment]
Just ran the script and got an error

```
./selectCUDADevices.sh: line 13: 1 *  : syntax error: operand expected (error token is "*  ")

```

**Comment by ptheywood** [comment]
I receive that error when I've not requested any GPUs, but with `#$ -l gpu=2` it runs as intended.

Additionally the call to nvidia-smi fails on non-gpu nodes, so we should probably account for that case and produce a graceful error, rather than 
```
/var/spool/sge/sharc-node025/job_scripts/2572589: line 46: nvidia-smi: command not found
```

**Comment by ptheywood** [comment]
`getSGERequestedGPUCount` doesn't work in interactive sessions as `$JOB_ID` is unset.

**Comment by ptheywood** [comment]
https://gist.github.com/ptheywood/ce4e5a600216dd085cae5bd5802d35aa#file-selectcudadevices-sh-L26 I've updated the gist to ensure that nvidia-smi is available so on non-gpu nodes (or if nvidia-smi is not available) an meaningful error message will be produced. This does not solve the interactive job issue.

**Comment by ptheywood** [comment]
https://gist.github.com/ptheywood/ce4e5a600216dd085cae5bd5802d35aa

Now updated to correctly check for nvidia-smi, correctly handle gpu interactive sessions, and also handle qrsh based sessions (via @willfurnass).

**Comment by twinkarma** [comment]
Thanks for sorting this out guys! Changes updated to the PR.

**Comment by twinkarma** [comment]
@willfurnass are we happy with this? Can we start the merge?

**Comment by twinkarma** [comment]
Looks like the script is working for both interactive and batch sessions now. Shall we go ahead with this on the interim before we can implement a better solution? @willfurnass

**Comment by willfurnass** [comment]
As discussed, I'm keen to roll out the automatic setting of `CUDA_VISIBLE_DEVICES` ASAP as this will be much cleaner.

**Comment by twinkarma** [comment]
Cancelling this as the automatic `CUDA_VISIBLE_DEVICES` makes this PR obsolete.

**Pull request closed without merging**
