### PR TITLE
ShARC: CUDA/cuDNN updates and modulefile fixes

### PR DESCRIPTION
**Pull request by willfurnass**
- Installer/modulefile/docs for CUDA 10.1 and 10.2
- Installer/modulefile/docs for compatible version of cuDNN
- Tweak all CUDA modulefiles to 
    - set `CUDA_ROOT`, `CUDA_PATH` and `CUDA_HOME` to the CUDA install prefix (previously only `CUDA_HOME` set)
    - prepend paths to `CPATH` and `MANPATH`
- Note that CUDA 10.1 required by TensorFlow 2.1

Addresses #884, #897 and partly addresses #999

### CODE REVIEW

**Comment by willfurnass** [comment]
Cc @twinkarma

**Comment by willfurnass** [comment]
@ptheywood I'd be grateful for your comments on the modulefiles.

**Comment by ptheywood** [comment]
> @ptheywood I'd be grateful for your comments on the modulefiles.

They look sensible and thorough to me.

**Comment by willfurnass** [comment]
@ptheywood Thanks for the review.

**Pull request merged**
