### PR TITLE
Document how to use Go

### PR DESCRIPTION
**Pull request by drj11**

### CODE REVIEW

**Comment by willfurnass** [comment]
Mostly LGTM.  Some suggestions:
 - Make URLs hyperlinks? 
 - Any need to mention `GOROOT` / `GOPATH`? (the answer to this may be 'no')

**Comment by drj11** [comment]
So, the whole `GOROOT` / `GOPATH` is something we avoid by using `conda`.
A later improvement to this document would to add the section: "ok, so _you_ know how Go is ordinarily organised; let's explain what conda has done".

**Comment by willfurnass** [comment]
Fair enough.  Could you convert the URLs to hyperlinks?

**Comment by drj11** [comment]
Yes, will add hyperlinks

**Comment by drj11** [comment]
I converted one of the URLs to an ordinary hyperlink.

For the remainder I think it's useful to see and know the actual URL (and of course, in the rendered HTML document they appear as hyperlinks too).

Please reconsider merging.

**Pull request merged**
