### PR TITLE
Add email support template

### PR DESCRIPTION
**Pull request by nahceigna**
Hi all,

I added the email support template in [Need help?](https://docs.hpc.shef.ac.uk/en/latest/help.html#general-hpc-problems) section to provide a guidance on how to best ask for support.

Issue #1963

### CODE REVIEW

**Comment by nahceigna** [comment]
> LGTM for the most part, might just want to:
> 
> 1. Extend the template a little to also request the job log files.
> 2. Have the user first confirm they've checked the FAQ page (provide this as a link).
> 3. Provide the template as a copy pasteable block as well.
> 
> Some folks may only use GMail and I don't know if clicking the link will open a GMail draft as we would desire.

@jkwmoore Thanks for your suggestions! Since the FAQ page is already referenced in the previous paragraph, do we need to confirm it with the users again in the paragraph discussing the email template?

**Review by jkwmoore — COMMENTED** [review]
I was thinking of having it in the body of the email to essentially "trick" people into actually going and having a look. It's one of the kinda naughty psychological tricks to make people actually go do it as most people won't want to lie to us in their opening email for help.

**Comment by nikishe** [comment]
Looks great. Only recommendation is probably to emphasize / encourage them to send scripts and logs as txt attachments rather than them  to paste them in the email; as this can get very messy if the odd person decided to paste 1000 lines of code/logs into the email.

**Review by nikishe — APPROVED** [review]
LGTM. Good work on the email template link.

**Review by jkwmoore — COMMENTED** [review]
Not sure the email subject makes sense to me. Might be an idea to go with something like

Subject: "HPC Help request - [CLUSTER NAME] - [SHORT DESCRIPTION]"

Or something similar that will help support staff understand, assess effort and prioritise tickets at a glance. Besides that, looks good to merge.

**Review by nikishe — APPROVED** [review]

**Review by jkwmoore — APPROVED** [review]

**Pull request merged**
