### PR TITLE
Adding HW accelerated session details to ShARC hierarchy

### PR DESCRIPTION
**Pull request by jkwmoore**
Ported and adjusted from Iceberg - may need further tidy up and / or new figures.

### CODE REVIEW

**Review by willfurnass — COMMENTED** [review]
Isn't this covered by the Iceberg docs reworking?

**Comment by jkwmoore** [comment]
Seemed a bit nested in here to be honest: https://docs.hpc.shef.ac.uk/en/latest/iceberg/accessing/hw-accel-gfx.html#

Is it present elsewhere / linked in from elsewhere?

**Comment by willfurnass** [comment]
Agreed; see suggested location in https://github.com/rcgsheffield/sheffield_hpc/pull/1139

**Comment by jkwmoore** [comment]
Ah yes, I did comment on this last Friday.  How soon are we likely to have qsh-vis sessions on Bess? If it isn't that soon I would probably put it under ShARC for now to try to avoid some confusion.

That said I do not feel particularly strongly about either.

**Comment by willfurnass** [comment]
My preference would be to close this, get the Iceberg-related changes merged then move on to consider accel vis for Bessemer as a separate Issue.

**Comment by jkwmoore** [comment]
Fair - I'm happy with the ICEBERG merge. Closing.

**Pull request closed without merging**
