### PR TITLE
Updated module files for Torch, Caffe and NCCL

### PR DESCRIPTION
**Pull request by twinkarma**
Can you please copy the module file on to the system as well so I can get other people to start testing?

### CODE REVIEW

**Comment by willfurnass** [comment]
Done.

**Comment by willfurnass** [comment]
I've noticed that your modulefiles are dependent on the `anacondaV-X.Y.Z` modules.  I 
```bash
$ fgrep -R anaconda /usr/local/modulefiles/
/usr/local/modulefiles/apps/python/.conda-environment.tcl:conflict apps/python/anaconda2-4.2.0 apps/python/anaconda3-4.2.0
/usr/local/modulefiles/apps/python/anaconda3-4.2.0:## anaconda module file
/usr/local/modulefiles/apps/python/anaconda3-4.2.0:activateenv anaconda3-4.2.0
/usr/local/modulefiles/apps/python/anaconda2-4.2.0:## anaconda module file
/usr/local/modulefiles/apps/python/anaconda2-4.2.0:#set anacondas glob -tails -path /usr/local/modulefiles apps/python/anaconda*
/usr/local/modulefiles/apps/python/anaconda2-4.2.0:#puts $anacondas
/usr/local/modulefiles/apps/python/anaconda2-4.2.0:activateenv anaconda2-4.2.0
/usr/local/modulefiles/libs/torch/7/gcc-4.9.4-cuda-8.0-cudnn-5.1-conda-3.4-TESTING:module load apps/python/anaconda3-4.2.0
/usr/local/modulefiles/libs/torch/nvidia-7/gcc-4.9.4-cuda-8.0-cudnn-5.1-conda-3.4-TESTING:module load apps/python/anaconda3-4.2.0
/usr/local/modulefiles/libs/caffe/nvidia-0.15.13/gcc-4.9.4-cuda-8.0-cudnn-5.1-python-2.7-conda-3.4-TESTING:module load apps/python/anaconda3-4.2.0
/usr/local/modulefiles/libs/caffe/rc3/gcc-4.9.4-cuda-8.0-cudnn-5.1-conda-3.4-TESTING:module load apps/python/anaconda3-4.2.0
```
There are no guarantees that the packages in the corresponding anacondaV-X.Y.Z conda environments won't be upgraded in a way that breaks the Caffe and Torch installs.  It would therefore make sense to create dedicated conda environments for each (or a single conda environment for both) then activate this within the modulefile as it is done in the following:

`/usr/local/modulefiles/apps/python/anaconda3-4.2.0`

**Comment by karmauk** [comment]
The new Torch and Caffe module builds are no longer dependent on Conda and
the module load was left there as an oversight.

It should not cause problem to leave it as it is for now and they will be
removed in the next update.

**Comment by twinkarma** [comment]
@willfurnass Got the following error during build

```
 /home/travis/build/rcgsheffield/sheffield_hpc/iceberg/software/apps/macaulay2.rst:: WARNING: unusable reference target found: /Macaulay2/current/share/doc/Macaulay2/IntegralClosure/html/
```

It came from the merged master branch of the main repo. How did this get through the build?

**Comment by willfurnass** [comment]
@twinkarma Not sure.  That URL should be http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.9.2/share/doc/Macaulay2/IntegralClosure/html/

**Comment by twinkarma** [comment]
Just noticed that as well... fixed it now.

**Comment by twinkarma** [comment]
@willfurnass I have no idea what's making it not build. Getting a too deeply nested error but I've not sectioned anything deeper than existing documents.

**Comment by twinkarma** [comment]
@willfurnass Nevermind, I think I found the problem.

**Comment by twinkarma** [comment]
@willfurnass The docs should be ready now. Can we look to merging to the main repo?

**Comment by mondus** [comment]
@willfurnass Will can this PR be merged as it contains some useful documentation on GPU DL software which people in the department are requesting. This PR also addresses all the issues highlighted by PR #538 . #538 can be closed.

**Comment by willfurnass** [comment]
Looks pretty much good to merge bar:
 - check cluster name and GCC module file name on ShARC GPU page (should be ShARC, not Iceberg)
 - I think we can now recommend qrshx over qsh (qsh) and should use it in our examples
 - max GPUs that can request for interactive use on ShARC is 8, not 4.  Also, would be good to link to the [existing ShARC spec](http://docs.hpc.shef.ac.uk/en/latest/sharc/cluster_specs.html) rather than duplicate info, although feel free to add in any info you think is missing from the ShARC spec page.

**Comment by willfurnass** [comment]
@twinkarma Happy for me to merge?

**Comment by twinkarma** [comment]
Yes it's ready to go!

**Comment by willfurnass** [comment]
Megamerge done!

**Comment by twinkarma** [comment]
Nice one!

**Pull request merged**
