### PR TITLE
Add R on Bessemer

### PR DESCRIPTION
**Pull request by willfurnass**
It's just R built using / depending on the `foss-2019b` toolchain.  No 3rd-party R pkgs installed.  Can install R packages such as rgdal and rgeos etc in due course.  Can also install R built with an `intel` toolchain if requested too.

### CODE REVIEW

**Comment by willfurnass** [comment]
Still WIP as a dependency (a Python easyconfig) failed to build...

**Review by jkwmoore — COMMENTED** [review]
All seems fine, only comment is whether we want to match the libraries on ShARC and make further builds compiled with the Intel Compiler available (I know this is likely non-trivial.)

**Comment by willfurnass** [comment]
> All seems fine, 

Ta.

> only comment is whether we want to match the libraries on ShARC and make further builds compiled with the Intel Compiler available (I know this is likely non-trivial.)

For libs such as rgdal etc?

**Comment by willfurnass** [comment]
Can add in due course.  Think it's important to get this merged now.

**Pull request merged**
