### PR TITLE
Added new caffe singularity images, updated DL docs

### PR DESCRIPTION
**Pull request by twinkarma**

### CODE REVIEW

**Comment by willfurnass** [comment]
@twinkarma NB Travis CI could not build your PR.

**Comment by twinkarma** [comment]
@willfurnass It builds fine on my local machine and Travis doesn't give specific errors. Any ideas what could be wrong?

**Comment by willfurnass** [comment]
The build timed out; I've kicked off another.

**Comment by twinkarma** [comment]
@willfurnass Looks like something's just gone a bit wrong with the build process that particular time then.

**Pull request merged**
