### PR TITLE
Update paths LSDYNA examples

### PR DESCRIPTION
**Pull request by Carldkennedy**
Update paths LSDYNA examples to include correct paths with $ANSYSPATH which has been added to module files

### CODE REVIEW

**Comment by Carldkennedy** [comment]
```
#!/bin/bash
ansys_versions=$(module -t --redirect avail |& grep -i "ANSYS/")

for version in $ansys_versions
do
    module purge
    ml $version
    ls $EBROOTANSYS
done
```
easybuild  install_licconfig.log  install.log  shared_files  v193
easybuild  install_licconfig.log  install.log  shared_files  v194
easybuild  install_licconfig.log  install.log  shared_files  v194
install.err  install_licconfig.log  install.log  shared_files  v201
install_licconfig.log  install.log  shared_files  v202
install_licconfig.log  install.log  shared_files  v211
install_licconfig.log  install.log  shared_files  v212
install_licconfig.log  install.log  shared_files  v222

**Comment by Carldkennedy** [comment]
Thanks @jkwmoore. Added ANSYSPATH to module files.

**Comment by Carldkennedy** [comment]
Example addition to module files:
```
-- For accessing executables and libraries 
setenv("ANSYSPATH", pathJoin(root, "v232"))
```
Added to hook.py
```
    if self.name == 'ANSYS':
        # Add ANSYSPATH, see also: https://github.com/rcgsheffield/sheffield_hpc/pull/1958
        self.log.info("[pre-module hook] Add ANSYSPATH, see also: https://github.com/rcgsheffield/sheffield_hpc/pull/1958")

        with self.cfg.disable_templating():
            ansys_path = os.path.join(self.installdir, self.ansysver)
            self.cfg['modextravars'].update({'ANSYSPATH': ansys_path})
 ```

**Review by nikishe — APPROVED** [review]
Passing based on carls confirmation of the test results

**Pull request merged**
