### PR TITLE
Update old and insecure Python dependencies

### PR DESCRIPTION
**Pull request by willfurnass**

### CODE REVIEW

**Comment by jkwmoore** [comment]
This has passed the auto test - has it had any affect / likely to have any effect on the generated docs themselves (GUI display etc...) anyone had a look?

**Review by jkwmoore — COMMENTED** [review]
Nothing in here looks like it will affect the generated document GUI display tbh.

**Comment by willfurnass** [comment]
Think the greatest risk is from the Jinja major version bump.  Will review shortly.

**Comment by willfurnass** [comment]
Think @jkwmoore  + dependabot have addressed the related issues, so closing.

**Pull request closed without merging**
