### PR TITLE
Update Bede page now N8 CIR docs and Bede both live

### PR DESCRIPTION
**Pull request by willfurnass**
- Bede now live so need to use present tense
- Refactored to state most suitable workflows at top of page
- Simplified specifications
- Signposted to new Bede docs

### CODE REVIEW

**Comment by willfurnass** [comment]
@ptheywood @mikeg64 Going to merge this before the RITF today.  If you got chance to review before then that would be great but no worries if not.

**Review by ptheywood — APPROVED** [review]
Looks good to me. 

Is it worth mentioning host memory (just to match the bede docs, 512GB for v100 nodes, 256GB for infer nodes)?

Some slightly odd margins for the nested lists, though that's a general comment (and I think v. common for rtd)

**Comment by willfurnass** [comment]
@ptheywood Thanks for the suggestion re RAM/node; updated the PR.  Not going to faff with .rst formatting / CSS with this PR given it's important to get it merged before the RITF.

**Comment by mikeg64** [comment]
Take care Bede is live but at Sheffield it's in beta phase - still getting processes in place - testing - allowing some beta users

**Comment by willfurnass** [comment]
@mikeg64 Added caveats to that effect via PR #1127.

**Pull request merged**
