### PR TITLE
Change tab order

### PR DESCRIPTION
**Pull request by Carldkennedy**
Reordering of tabs (newest to oldest cluster)
And a few corrections: Sharc to ShARC

### CODE REVIEW

**Review by jkwmoore — APPROVED** [review]
Added some corrections to the cluster naming within the shared area section (my previous error) - LGTM.

**Comment by jkwmoore** [comment]
This is difficult to review using the diff - recommend looking at the files in your IDE.

**Comment by willfurnass** [comment]
Quite a few changes here - is this just reordering tabs?  PR description might help :)

**Comment by jkwmoore** [comment]
> Quite a few changes here - is this just reordering tabs? PR description might help :)

Aye, sorting everything to go: Stanage --> Bessemer --> ShARC.

**Comment by Carldkennedy** [comment]
> Quite a few changes here - is this just reordering tabs? PR description might help :)

Apologies @willfurnass. Edited the description.

**Review by nikishe — APPROVED** [review]

**Pull request merged**
