### PR TITLE
Add custom Google search.

### PR DESCRIPTION
**Pull request by jkwmoore**
Does what it says on the tin, the current scripting is setup using my Uni Google account but in principle it can be swapped as needed at:

https://cse.google.com/cse/all 

AFAIK this is good to merge immediately. I am a magician.

### CODE REVIEW

**Comment by jkwmoore** [comment]
image

image

**Comment by jkwmoore** [comment]
This works locally but is failing in Github CI/CD :/

**Comment by willfurnass** [comment]
We already have search via Sphinx?

**Comment by jkwmoore** [comment]
And the Sphinx search is steaming white hot garbage!

**Review by nikishe — APPROVED** [review]

**Comment by nikishe** [comment]
> We already have search via Sphinx?

Sphinx search leads to issues like SHEF 2401 11534. Where the user doesn't get what they want and leads to picking wrong docs. Happy to demo the issue this afternoon

**Comment by jkwmoore** [comment]
N.b. so long as folks investigate the process for creating the custom search engine (CSE) and are happy with how that works I will merge.

Details on implementation here: https://github.com/sphinx-doc/sphinx/issues/36#issuecomment-464066114

It will add some small extra steps if it ever needs updating to a new CSE to reapply the theming etc...

**Review by nikishe — APPROVED** [review]

**Review by Carldkennedy — APPROVED** [review]

**Pull request merged**
