### PR TITLE
Added cuDNN install and module scripts. Updated cuDNN documentation. Updated Theano documentation.

### PR DESCRIPTION
**Pull request by karmauk**

### CODE REVIEW

**Comment by willfurnass** [comment]
Looks good; thanks for this!  A few minor things:

* `-P gpu` is not needed (any more)
* Best to enclose filenames (e.g. `.theanorc`) in double back-ticks to ensure they're rendered as fixed width fonts in the `.rst` files
* It would be good to include the name of the cluster in the reference at the top of the cuDNN page e.g. 
```
.. _iceberg_cudnn::
```
* Within the Theano page could include a link to the cuDNN page for info on what versions are available e.g. something like:

```
blahblahblah (:ref:`several versions <iceberg_cudnn>` of cuDNN and CUDA are available)
```

* Better to recommend conda as the default way to install Theano + dependencies?
* Should add a note to the installation instructions that cuDNN installers are available in `/usr/local/media/protected`

**Comment by karmauk** [comment]
I've changed the documentation according to your suggestion. The only thing I didn't change is the use of conda instead of pip to install Theano. This approach does not appear on their official documentation, or any forum threads and I have not had an opportunity to test it so I will leave it for possible alteration in the future.

**Comment by willfurnass** [comment]
A couple more things (then we're ready to merge):

 * `--l` in qsh command should be `-l`
 * Could I annoyingly ask for modulefiles and install dirs to have the form `libs/binlibs/cudnn/5.0-cuda-7.5` (for consistency with other packages on the system)?

**Comment by karmauk** [comment]
I've made the changes as suggested. I've also made the modules name more concise by stating the full CUDA version that gets loaded i.e. `5.0-cuda-8.0.44`, is this better or should I revert to `5.0-cuda-8.0`?

**Comment by willfurnass** [comment]
Cheers.  It's not clear whether we want to install 5.0, 5.1 or both?  (search for 5.1 and 5.0 here: https://github.com/rcgsheffield/sheffield_hpc/pull/451/files#diff-c1267d039593c843d94cdfae532befad) 

If we just want 5.1 then we should ditch all the 5.0 stuff.  Alternatively, we need to ensure that only 5.1 is mentioned in the `.rst` files.

**Comment by karmauk** [comment]
We might as well go all in with 5.1 so I've replaced all the previous install and module scripts with the new version.

**Comment by willfurnass** [comment]
Packages and modulefiles now installed.

Made the following changes to the install scripts for Iceberg:

```
3,18c3,15
< #The script installs cuDNN 5.1 for CUDA 7.5 and CUDA 8.0 in to the correct ShARC directory
< 
< #The binaries can be downloaded from Nvidia at https://developer.nvidia.com/cudnn
< 
< #We assume that the .tgz fils are in current working directory
< 
< #Install cuDNN 5.1 for CUDA 7.5
< install_dir=/usr/local/packages/libs/cudnn/5.1/binary-cuda-7.5
< mkdir -p $install_dir
< tar -C $install_dir -xvzf ./cudnn-7.5-linux-x64-v5.1-ga.tgz 
< 
< #Install cuDNN 5.1 for CUDA 8.0
< install_dir=/usr/local/packages/libs/cudnn/5.1/binary-cuda-8.0
< mkdir -p $install_dir
< tar -C $install_dir -xvzf ./cudnn-8.0-linux-x64-v5.1-ga.tgz 
< 
---
> # The script installs cuDNN 5.1 for CUDA 7.5 and CUDA 8.0 in to the correct ShARC directory
> # The binaries can be downloaded from NVIDIA at https://developer.nvidia.com/cudnn
> # and need to be saved in $MEDIA_DIR (see below)
> 
> VERS=5.1
> MEDIA_DIR=/usr/local/media/protected/cuDNN
> PREFIX_BASE=/usr/local/packages/libs/cudnn/$VERS
> 
> for cuda_vers in 7.5 8.0; do 
>     install_dir=${PREFIX_BASE}/binary-cuda-${cuda_vers}
>     mkdir -p $install_dir
>     tar -C $install_dir -xvzf ${MEDIA_DIR}/cudnn-${cuda_vers}-linux-x64-v${VERS}.tgz 
> done
19a17,18
> sudo chgrp -R app-admins $PREFIX_BASE
> sudo chmod -R g+w $PREFIX_BASE
```

**Comment by willfurnass** [comment]
@karmauk Please could you remove all references to cuDNN 5.0 from this pull request and update the links to install scripts / modulefiles from the `.rst` files so the look like those in [this file](https://raw.githubusercontent.com/rcgsheffield/sheffield_hpc/master/sharc/software/apps/java.rst)?  This way of referencing files ensures that the validity of links is checked at build-time.

**Comment by karmauk** [comment]
The media directories does not appear for me. Does this mean that I don't have permission or that I don't have access?

Also I had a look at the java.srt file and the only difference that I saw was a double underline instead of a single underline. Is that correct or am I missing something?

**Comment by willfurnass** [comment]
I've already run the install scripts and set up the modulefiles.  I've just now also given you write access to the media dirs in case you need it in future.

Re the links your download links look like:

```
	- `cuDNN 5.1 for CUDA 7.5 <https://github.com/rcgsheffield/sheffield_hpc/tree/master/iceberg/software/modulefiles/libs/binlibs/cudnn/5.0-cuda-7.5.18>`_
	- `cuDNN 5.1 for CUDA 8.0 <https://github.com/rcgsheffield/sheffield_hpc/tree/master/iceberg/software/modulefiles/libs/binlibs/cudnn/5.0-cuda-8.0.44>`_
```
whereas what would be best are links like
```
	- :download:`cuDNN 5.1 for CUDA 7.5 </iceberg/software/modulefiles/libs/binlibs/cudnn/5.0-cuda-7.5.18>`
	- :download:`cuDNN 5.1 for CUDA 8.0 </iceberg/software/modulefiles/libs/binlibs/cudnn/5.0-cuda-8.0.44>`
```
as sphinx will check their validity at build-time.

**Comment by karmauk** [comment]
Thanks for getting it all installed by the way.

You said that you updated the the install script but I don't see any updates in the changes list or the main repo. Do I just copy the code above in to mine and commit or is there a way to properly do it?

**Comment by willfurnass** [comment]
I think the cleanest ways for me to amend your pull requests are 
 - for you to grant me write access to your fork and for me to directly push commits to it or
 - for me to checkout your fork and create a new pull request from it.  

I've not tried doing either before, so for expediency I just pasted diffs into the PR (apologies for not making this clear).  You can apply these using the `patch` utility:

```bash
patch originalfile file.patch
```

Also, you'll notice that the continuous integration tests are not passing: this is because you need to remove `https://github.com/rcgsheffield/sheffield_hpc/tree/master` from all your `:download:` URLs.  You'll also need to [cherry-pick](http://technosophos.com/2009/12/04/git-cherry-picking-move-small-code-patches-across-branches.html) commit a36e59f2f912a6ee3155306d55cd37cb6775e51c to work around a recently discovered issue with out continuous integration setup (#474).

Finally, note that we're still referencing cuDNN 5.0 (search for "our example uses CUDA 8.0 with cuDNN 5.0").

**Comment by karmauk** [comment]
Tried running ``git cherry-pick a36e59f`` but was getting error:

```
error: Commit a36e59f2f912a6ee3155306d55cd37cb6775e51c is a merge but no -m option was given.
fatal: cherry-pick failed
```

When I tried to add the -m option I get

```
error: switch `m' expects a numerical value

```

**Comment by willfurnass** [comment]
Hmm.  Perhaps try merging in the upstream/master branch instead; that will pick up the necessary commit.

**Comment by willfurnass** [comment]
The Travis CI report suggests there's an issue with `:download:` path to an install script.

**Comment by karmauk** [comment]
So sorry about this. Hopefully everything's fixed now.

**Pull request merged**
