### PR TITLE
2021 position of apptainersingularity pages in tocs is unexpected

### PR DESCRIPTION
**Pull request by Carldkennedy**
Renamed singularity.rst to apptainer.rst
Added stub for singularity

### CODE REVIEW

**Comment by Carldkennedy** [comment]
However, Singularity/Apptainer still shows along with  Apptainer/Singularity in TOC even though added `:hidden: yes` to stub
Should we keep this double entry?

**Comment by willfurnass** [comment]
I don't think we need 'Singularity' entries in TOCs provided that people can still find mention of Singularity on Apptainer pages via the site's search functionality.

**Comment by willfurnass** [comment]
I don't think we need 'Singularity' entries in TOCs provided that people can still find mention of Singularity on Apptainer pages via the site's search functionality.

**Comment by willfurnass** [comment]
I don't think we need 'Singularity' entries in TOCs provided that people can still find mention of Singularity on Apptainer pages via the site's search functionality.

**Review by nikishe — APPROVED** [review]

**Review by nikishe — CHANGES_REQUESTED** [review]
/home/runner/work/sheffield_hpc/sheffield_hpc/stanage/software/apps/index.rst:6:toctree contains reference to document 'stanage/software/apps/singularity'

**Comment by Carldkennedy** [comment]
Singularity was still being picked up by toc even though orphan directive added to .rst

**Comment by Carldkennedy** [comment]
Conflicting opinions here. Does anyone knows of a fix that would hide singularity from the toc (other than `:orphan:` directive)

**Comment by jkwmoore** [comment]
I have added a commit which should achieve what we want. Let me know what people think. If we are happy with this we should also add a small amount of info to the README.

**Comment by Carldkennedy** [comment]
LGTM @jkwmoore, thank you!

**Review by nikishe — APPROVED** [review]

**Pull request merged**
