### PR TITLE
Warning note added for Iceberg Decommissioning

### PR DESCRIPTION
**Pull request by jkwmoore**
Warning note added to all Iceberg pages - do we wish to add this to other pages?

### CODE REVIEW

**Comment by desmfryan** [comment]
Hi James

Looks good to me.

Cheers,

Des

**Comment by willfurnass** [comment]
Nice idea.  Cleaner to add the warning via a separate file referenced by the .reStructuredText 'include' directive?  Would more easily allow that warning to be updated.  See https://sublime-and-sphinx-guide.readthedocs.io/en/latest/reuse.html#include-a-shared-file

**Review by willfurnass — COMMENTED** [review]
https://sublime-and-sphinx-guide.readthedocs.io/en/latest/reuse.html#include-a-shared-file

**Comment by jkwmoore** [comment]
> Caution
>Include paths are relative to the file in the document project, not the file in shared content.


Unfortunately including files is relative to the file you are compiling at the time so depending on where that .rst file is in the folder hierarchy will need a different file path for the include which is a non-trivial thing to fix.

I've tested this and it is indeed relative - we could ofc write something to parse what level of directory it is in and correctly add the  include path but it's Friday at 17:13 so I'm not going to look at that now and it probably isn't worth the time anyway :)

**Comment by willfurnass** [comment]
Ah.  You could have one warning.rst in `iceberg/` then a different relative `.. include::` path in each of the following?
 
1. `iceberg/software/*/*.rst`
1. `iceberg/*/*.rst`
1. `iceberg/*.rst`

**Comment by jkwmoore** [comment]
That should be using include files everywhere that is needed but there's going to be a lot of warnings when it generated the files.

**Comment by jkwmoore** [comment]
Did I just kill the builder with excessive warning messages? :/ Built it fine locally.

**Pull request merged**
