### PR TITLE
Update to reflect optimal affinity settings for Bessmer

### PR DESCRIPTION
**Pull request by jkwmoore**
Update adds the -affinity=off to the commands where needed and provides explanation for this setting.

This is the PR for https://github.com/rcgsheffield/sheffield_hpc/issues/1082

### CODE REVIEW

**Comment by willfurnass** [comment]
Can we set this as a default for those applications somehow?

**Comment by jkwmoore** [comment]
Waiting on a reply from ANSYS :)

**Comment by jkwmoore** [comment]
As per ANSYS' reply - fix is proposed instead to use the tested env var rather than asking used to use command flags.

Amended as such - changes to module files are pending (likely tomorrow morning) subject to change request being approved / implemented.

**Review by desmfryan — APPROVED** [review]
Hi James

Looks fine. I will run a quick Fluent job on Bessemer as a pretend user :+1: 

Cheers,

Des

**Pull request merged**
