### PR TITLE
Add Stanage PROJ and BOOST docs

### PR DESCRIPTION
**Pull request by Carldkennedy**

### CODE REVIEW

**Comment by jkwmoore** [comment]
Broadly LGTM few points:

- Are we missing some software in the 12.X series for Boost.
- Should the PROJ title just be PROJ rather than PROJ.9 (since it documents 7, 8 and 9.)

**Review by nikishe — APPROVED** [review]
LGTM

**Comment by Carldkennedy** [comment]
Boost has been rebuilt and tested with new zstd dependency

**Comment by jkwmoore** [comment]
> Boost has been rebuilt and tested with new zstd dependency See https://docs.easybuild.io/release-notes/#release_notes_eb471 and [easybuilders/easybuild-easyconfigs#17482](https://github.com/easybuilders/easybuild-easyconfigs/pull/17482)

For clarity for us looking back on this, I assume this is all the installed Boost modules on Stanage?

**Pull request merged**
