### PR TITLE
Notes on how to update filestore flowchart

### PR DESCRIPTION
**Pull request by willfurnass**

### CODE REVIEW

**Comment by jkwmoore** [comment]
Shall I cherry pick my HTML comments in https://github.com/rcgsheffield/sheffield_hpc/pull/1517 across then merge both in one PR?

**Comment by jkwmoore** [comment]
I'm not forseeing much if any changes will be needed to the "helpy" bits around the diagram and my approach to changing it would primarily be to look at the source of the .rst. A happy medium perhaps would be to make the HTML / rst comments point at the readme section in the Github repo?

**Comment by willfurnass** [comment]
I've migrated my notes to the HTML comment in `filestore.rst`

**Review by jkwmoore — APPROVED** [review]
LGTM.

**Pull request merged**
