### PR TITLE
CUDA + cuDNN changes for SHARC

### PR DESCRIPTION
**Pull request by willfurnass**
Install CUDA 9.1, CuDNN 7.0 for CUDA 9.1 and for CUDA 8.0:
- [x] write install scripts
- [x] write modulefiles
- [x] update docs
- [x] test - built and ran several CUDA example progs 
- [x] deploy

Also, 
- [x] note which versions of CUDA require which versions of GCC.
- [x] ensure that CUDA module files on ShARC are mutually exclusive.

### CODE REVIEW

**Comment by willfurnass** [comment]
NB CUDA 9.1 requires NVIDIA driver version 387.26 but at present 384.81 is the recommended version for P100 GPUs; trying to use CUDA 9.1 with the older graphic driver results in:

```
cudaGetDeviceProperties returned 35
-> CUDA driver version is insufficient for CUDA runtime version
CUDA error at bandwidthTest.cu:242 code=35(cudaErrorInsufficientDriver) "cudaSetDevice(currentDevice)"
```

Going to wait to see the recommended graphics driver for P100 cards is revised over the next week or so (as CUDA 9.1 was released only a couple of days ago).

**Comment by willfurnass** [comment]
NB cuDNN 6.0 has been installed via a separate PR (#761)

**Comment by willfurnass** [comment]
From @ptheywood

> Looks like new drivers should be out this month for telsas, as they are pushing out drivers with mitigation for spectre in (probably jsut recompiling with up to date gcc/llvm with the new compiler flags which block speculative execution). 
> Not sure if the driver this week will be up to date enough for 9.1, but the week of jan 22nd should be. 
> 
> https://nvidia.custhelp.com/app/answers/detail/a_id/4611/related/1

**Comment by ptheywood** [comment]
@willfurnass 
A new recommended driver for P100s has been released today, 384.111, including the spectre mitigation(s), however this is still only for CUDA 9.0 or earlier. 

A CUDA 9.1 recommended driver should be available in ~ 2 weeks.

http://www.nvidia.co.uk/download/driverResults.aspx/129547/en-uk

**Comment by willfurnass** [comment]
@ptheywood The 390.12 driver is the current recommended driver for the P100, includes updates re Meltdown/Spectre and supports CUDA 9.1:

http://www.nvidia.com/download/driverResults.aspx/130188/en-us

**Comment by willfurnass** [comment]
NVIDIA Driver 390.30 now being deployed on machines with P100 GPUs in ShARC.

NB Need to patch CUDA 9.1 install:  https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=RHEL&target_version=7&target_type=runfilelocal

**Comment by willfurnass** [comment]
@ptheywood Please could you enumerate some samples we should run, other than cublas matmul, to check a) basic functionality (inc. NVLINK) and b) performance.

**Comment by ptheywood** [comment]
Whilst looking up the details of the examples I've stumbelled across NVVS (NVIDIA Validation Suite) which looks like it is designed for this type of task:

> The NVIDIA Validation Suite (NVVS) is the system administrator and cluster manager's tool for detecting and troubleshooting common problems affecting NVIDIA® Tesla™ GPUs in a high performance computing environments. NVVS focuses on software and system configuration issues, diagnostics, topological concerns, and relative performance.

http://docs.nvidia.com/deploy/nvvs-user-guide/index.html

I've no experience with this but a quick skim of the documentation makes it look like what we need. 



As for which of the duda examples weet are most appropriate: 

In the `1_Utilities/` directory, `bandwidthTest`, `p2pBandwidthLatencyTest` and `topologyQuery` should all provide some form of reference values and ensure things are running as intended.
`deviceQuery` is useful for finding the exact spec of cards in a system, but we already know what we have in ShARC so it's not quite so useful.

In `0_Simple` `matrixMul` and `matrixMulCUBLAS` do provide a good reference case, however they expliticly state not the use as benchmarking tools, and the problem size is a little small for devices such as P100/V100. 

`5_Simulations/nbody` is a good demo, although I believe it includes a GL visualisation so I'm not sure how appropriate that is to ShARC. 

There are other exmaples which demonstrate certain features that could be used to make sure things are behaving correctly, but I think NVVS seems like a better choice anyway.

**Comment by willfurnass** [comment]
Re NVVS (from the release notes of the latest NVIDIA Data Centre GPU Manager (DCGM)): 

> Running NVVS as a standalone utility is now deprecated. All functionality of NVVS can now be accessed via the DCGM command line interface (see `dcgmi diag -h`).

NB only an older DCGM is installed on ShARC's DGX-1; probably should be upgraded.

**Comment by willfurnass** [comment]
Going to merge this PR and create separate Issues for
 - Upgrading DCGM/NVVS
 - Documenting results of running CUDA demo progs recommended by @ptheywood

**Pull request merged**
