### PR TITLE
Add cuDNN 4 for ShARC + CUDA 7.0/7.5

### PR DESCRIPTION
**Pull request by willfurnass**
As requested by a user.

### CODE REVIEW

**Comment by willfurnass** [comment]
Hmm, can't run the `mnistCUDNN` example prog on V100 GPUs:

```console
[te1st@sharc-node168 mnistCUDNN]$ make
/usr/local/packages/libs/CUDA/7.5.18/binary/cuda/bin/nvcc -ccbin g++ -I/usr/local/packages/libs/CUDA/7.5.18/binary/cuda/include -IFreeImage/include -IUtilNPP  -m64    -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_52,code=compute_52 -o fp16_dev.o -c fp16_dev.cu
g++ -I/usr/local/packages/libs/CUDA/7.5.18/binary/cuda/include -IFreeImage/include -IUtilNPP   -o fp16_emu.o -c fp16_emu.cpp                                                                 
g++ -I/usr/local/packages/libs/CUDA/7.5.18/binary/cuda/include -IFreeImage/include -IUtilNPP   -o mnistCUDNN.o -c mnistCUDNN.cpp                                                             
/usr/local/packages/libs/CUDA/7.5.18/binary/cuda/bin/nvcc -ccbin g++   -m64      -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_52,code=compute_52 -o mnistCUDNN fp16_dev.o fp16_emu.o mnistCUDNN.o  -LFreeImage/lib/linux/x86_64 -LFreeImage/lib/linux -lcudart -lnppi -lnppc -lcublas -lcudnn -lfreeimage -lstdc++ -lm
[te1st@sharc-node168 mnistCUDNN]$ ./mnistCUDNN
cudnnGetVersion() : 4007 , CUDNN_VERSION from cudnn.h : 4007 (4.0.7)
Host compiler version : GCC 4.8.5
There are 1 CUDA capable devices on your machine :
device 0 : sms 80  Capabilities 7.0, SmClock 1380.0 Mhz, MemSize (Mb) 16160, MemClock 877.0 Mhz, Ecc=1, boardGroupID=0                                                                       
Using device 0

Testing single precision
Loading image data/one_28x28.pgm
Performing forward propagation ...
Testing cudnnGetConvolutionForwardAlgorithm ...
Fastest algorithm is Algo 1
Testing cudnnFindConvolutionForwardAlgorithm ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: 0.093216 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: 0.154656 time requiring 209360 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: 0.159776 time requiring 57600 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: 0.185344 time requiring 19508 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: 0.206848 time requiring 207360 memory
Resulting weights from Softmax:
0.0997550 0.0892810 0.1054468 0.1071846 0.0902156 0.1043498 0.0953814 0.0938049 0.1155469 0.0990339                                                                                          
Loading image data/three_28x28.pgm
Performing forward propagation ...
Resulting weights from Softmax:
0.0997550 0.0892810 0.1054468 0.1071846 0.0902156 0.1043498 0.0953814 0.0938049 0.1155469 0.0990339                                                                                          
Loading image data/five_28x28.pgm
Performing forward propagation ...
Resulting weights from Softmax:
0.0000000 0.0000008 0.0000000 0.0000002 0.0000000 0.9999820 0.0000154 0.0000000 0.0000012 0.0000006                                                                                          

Result of classification: 8 8 5

Test failed!
Prediction mismatch
mnistCUDNN.cpp:815
Aborting...
```

**Comment by willfurnass** [comment]
Ah, can run the example on a  K80.

**Comment by twinkarma** [comment]
I get a ```Test failed! Prediction mismatch``` as well on the DGX-1.

**Comment by willfurnass** [comment]
@twinkarma Noted in install+testing notes - should we make this info more prominent?

**Comment by twinkarma** [comment]
@willfurnass Definitely make the warning more prominent. New GPUs are meant to be backwards compatible so it's a bit worrying that it fails on both V100 and P100.

**Pull request merged**
