### PR TITLE
Clarify memory options in tables.

### PR DESCRIPTION
**Pull request by jkwmoore**
See: https://github.com/rcgsheffield/sheffield_hpc/issues/1079

### CODE REVIEW

**Review by willfurnass — COMMENTED** [review]
I agree that this section would benefit from revising but think it might help to introduce the `--mem-per-cpu` argument as this works in the same way as SGE's `rmem'.  Could also mention `--mem-per-gpu`.

**Comment by jkwmoore** [comment]
We might want to refactor the table on this page leaving blank section for comparison options where there is no clear alternative between SGE and SLURM - e.g. by SLURM by CPUs (not by node or by core) has no direct equiv in SGE (that I know of.)

**Comment by jkwmoore** [comment]
I'm going to close this as part of a larger refactoring is planned.

**Comment by jkwmoore** [comment]
I am going to re-open and merge this because that refactoring hasn't happened yet and I really don't want the docs staying wrong for any more time.

**Comment by jkwmoore** [comment]
Currently looks like - 
image

**Review by desmfryan — COMMENTED** [review]
Hi James

Some comments/suggestions:
-> means 'change to'

line 57 
to stat -> to start

line 129
-pe <env> -> -pe mpi

line 165
will be consumed -> will be run/executed 
Note: consumed will not mean anything to the general user

line 178:
consumed -> run/executed

line 261:
foo < foo.dat > foo.res      ->       foo foo.dat foo.res
note users may think they need to use < > around input files

line 268:
foo < foo.dat > foo.res      ->         foo foo.dat foo.res

line 363:
--mail-type=          ->      --mail-type=all

Cheers,

Des

**Comment by jkwmoore** [comment]
> 
> 
> Hi James
> 
> Some comments/suggestions:
> -> means 'change to'
> 
> line 57
> to stat -> to start
> 

Fixed.

> line 129
> -pe -> -pe mpi
> 

I suspect this has been set as  -pe <env> because we have mpi and mpi-rsh envs. (ANSYS has to be special ofc.)

> line 165
> will be consumed -> will be run/executed
> Note: consumed will not mean anything to the general user
> 

Fixed.

> line 178:
> consumed -> run/executed
> 

Fixed.

> line 261:
> foo < foo.dat > foo.res -> foo foo.dat foo.res
> note users may think they need to use < > around input files
> 

Fixed.

> line 268:
> foo < foo.dat > foo.res -> foo foo.dat foo.res
> 

Fixed. (But was 286 iirc.)


> line 363:
> --mail-type= -> --mail-type=all
> 

Fixed.

**Pull request merged**
