### PR TITLE
Update R&I team name

### PR DESCRIPTION
**Pull request by willfurnass**
We're now Research and Innovation team, not Research Computing Group.  Also updated link to more info on team.

### CODE REVIEW

**Comment by jkwmoore** [comment]
We also need to have a gander through / chat about the ITS wiki to sort this via grouping everyone under R&I and then tying the different services to the group (or sub-groups) too.

Was looking at this the other day and we have a bit of a mixture of different out of date groups but it might be a bit of a major refactor (and I don't want to arbirarily just start changing things on my own.)

**Review by jkwmoore — APPROVED** [review]
Changes LGTM but we also need to amend the help page (https://docs.hpc.shef.ac.uk/en/latest/help.html) and some other bits I suspect are floating about.

**Comment by willfurnass** [comment]
> Changes LGTM but we also need to amend the help page (https://docs.hpc.shef.ac.uk/en/latest/help.html) and some other bits I suspect are floating about.

Tried to do this with the amended commit.

**Review by jkwmoore — APPROVED** [review]
Double approve, LGTM. Will keep in mind updating this for our future docs also.

**Pull request merged**
