### PR TITLE
Added Julia documentation

### PR DESCRIPTION
**Pull request by Lizzydapsy**
I have included the documentation for julia in both software and modulefiles section of the document.

### CODE REVIEW

**Comment by desmfryan** [comment]
Hi Elizabeth

You are missing tags......so julia does not appear in the documentation. Check jags.rst for the correct format.

Thanks.

Des

**Comment by Lizzydapsy** [comment]
Missing tags now included.

**Comment by Lizzydapsy** [comment]
Added now, thanks.

**Comment by willfurnass** [comment]
@Lizzydapsy Have these changed been reverted somehow?

**Pull request closed without merging**
