### PR TITLE
Updated the sheffield hpc docs to reflect the newest version of Ansys software

### PR DESCRIPTION
**Pull request by Lizzydapsy**
Updated the sheffield hpc docs to reflect the newest version of Ansys software

### CODE REVIEW

**Comment by Lizzydapsy** [comment]
?

**Comment by Lizzydapsy** [comment]
oh, great

**Comment by jkwmoore** [comment]
Here's a nice list of some of the short hands that get used: https://www.freecodecamp.org/news/what-do-cryptic-github-comments-mean-9c1912bcc0a4/

**Comment by Lizzydapsy** [comment]
haha, thanks for the link. I had to quickly google LGTM :)

**Comment by willfurnass** [comment]
Nice work, cheers.

**Comment by Lizzydapsy** [comment]
@ Des, I intentionally did not changed that because it states "The arguments -sgepe mpi-rsh -sge are not required and will cause issues if used with Fluent 21.1 or above". The statement has captured 22.1 (in the word "above"). If I change that, then it will imply that using the argument with 21.1 will not have issues, which isn't right.

**Pull request closed without merging**
