### PR TITLE
Correction to Tesla K80 node total GPU memory

### PR DESCRIPTION
**Pull request by ptheywood**
Each K80 PCI-e device contains 2 GPUs, each with 12GB of memory.
The public K80 nodes each contain 4 phyiscal devices, corresponding to 8 GPUs and 96GiB total device memory, rather than 192 as previously stated.

This can be seen via `nvidia-smi` (which reports 11441 MiB of usable device memory per GPU)

```
Thu Oct 18 16:19:50 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:06:00.0 Off |                    0 |
| N/A   38C    P0    62W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:07:00.0 Off |                    0 |
| N/A   46C    P0    73W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 00000000:0A:00.0 Off |                    0 |
| N/A   35C    P0    61W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 00000000:0B:00.0 Off |                    0 |
| N/A   43C    P0    76W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla K80           Off  | 00000000:86:00.0 Off |                    0 |
| N/A   45C    P0    83W / 149W |  10920MiB / 11441MiB |     59%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla K80           Off  | 00000000:87:00.0 Off |                    0 |
| N/A   50C    P0    75W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla K80           Off  | 00000000:8A:00.0 Off |                    0 |
| N/A   35C    P0    61W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla K80           Off  | 00000000:8B:00.0 Off |                    0 |
| N/A   42C    P0    74W / 149W |      0MiB / 11441MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+

```

### CODE REVIEW

**Comment by willfurnass** [comment]
Should lines 61 and 63 be reworded to clarify the difference between hardware devices and logical GPUs?  At present, it's quite confusing.  Any suggestions for wording?

**Comment by ptheywood** [comment]
K80s are just a bit confusing. There doesn't seem to be consistency in the use of GPU when talking about K80's in Nvidia's documentation, being used to both refer to the pcie device and individual bits of silicon within the same paragraph

> The NVIDIA® Tesla® K80 graphics processing unit (GPU) is a PCI Express, dual-slot
> computing module in the Tesla (267 mm length) form factor comprising of two Tesla
> K80 GPUs. 
> [source](https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/tesla-product-literature/Tesla-K80-BoardSpec-07317-001-v05.pdf)

*Tesla K80 Accelerator* seems to be used to refer to the whole device in some cases, using GPUs to refer to the 2 GPUs within. Alternatively *board* is also used within the document.

> The Tesla K80 Accelerator has two Tesla GK210 GPUs. Characteristics for both GPUs are
as follows

The current reported performance values are also for the whole accelerator/board too:

> 4992 NVIDIA CUDA cores with a dual-GPU design
> Up to 2.91 teraflops double-precision performance with NVIDIA GPU Boost
> Up to 8.73 teraflops single-precision performance with NVIDIA GPU Boost
> 24 GB of GDDR5 memory
> [source](https://www.nvidia.com/en-gb/data-center/tesla-k80/)


So it seems probably best to go for 8 GPUs and 4 accelerators/boards? (I'd probably lean towards accelerator, although that's also an ambiguous term)

It's probably then best to list the specs per GPU, followed by per accelerator (or board) in brackets (for the easeist comparison to say the K40 specs on icerbergs pages)?


```
* GPUs: 8 x `NVIDIA Tesla K80`_ (4x dual GPU accelerators)

  * 12 GiB of GDDR5 memory per GPU (24 GiB per accelerator; 96 GiB per node)
  * Up to 1.455 Teraflops of double precision performance with NVIDIA GPU Boost per GPU (2.91 TFLOPS per accelerator)
  * Up to 4.37 Teraflops of single precision performance with NVIDIA GPU Boost per GPU (8.74 TFLOPS per accelerator)

```

**Comment by willfurnass** [comment]
I think your rewording works much better.  Users are far more likely to care about the number of GPUs, particularly as the scheduler and users don't have a sound way of managing affinity so to allocate whole accelerators if the number of GPUs requested is a even number.

Within a node is the memory within a dual-GPU accelerator (I like that phrase) any more unified from CUDA's perspective than the memory of all accelerators on the PCIe bus?

**Comment by ptheywood** [comment]
I think the memory is only accessible to the relevant GPU, the PCI-e bus must be shared between the GPUs, but i'm unsure if its time sliced or lane split between devices.

**Comment by willfurnass** [comment]
Thanks Pete!

**Comment by willfurnass** [comment]
> I think the memory is only accessible to the relevant GPU, the PCI-e bus must be shared between the GPUs, but i'm unsure if its time sliced or lane split between devices.

Don't think this is worth mentioning in the docs then.

**Pull request merged**
